# Rust Aliases
alias cg="cargo"
alias ccl="cg clean"
alias cch="cg check"
alias cb="cg build"
alias cr="cg run"
alias ca="cg add"
alias rn="rustup override set nightly"
alias cn="cg new"
alias ci="cg install"
alias cdoc="cg doc"
alias cdoc-open="cg doc --open"
alias cdoc-publish="cg doc --publish"
# Python Aliases
alias pymng="python3 manage.py"
alias pruns="pymng runserver"
alias pmigr="pymng migrate"
alias pmkmg="pymng makemigrations"
alias vv="virtualenv venv"
alias sv="source venv/bin/activate"
alias dea="deactivate"
alias pip:proxy="pip3 install --proxy http://10.23.201.11:3128"
# Poetry Aliases
alias ptr="poetry"
alias ptr:i="ptr install"
alias ptr:u="ptr update"
alias ptr:l="ptr list"
alias ptr:c="ptr check"
alias ptr:s="ptr show"
alias ptr:p="ptr publish"
alias ptr:d="ptr dev"
alias ptr:b="ptr build"
# Laravel, Composer Aliases
alias pa="php artisan"
alias pas="pa serve"
# Symfony Aliases
alias pbc="php bin/console"
alias sf:new="symfony new"
alias sf:rd="pbc router:debug"
alias sf:dsu="pbc doctrine:schema:update --force"
alias sf:dsd="pbc doctrine:schema:drop --force"
alias phpini="sudo nano /etc/php5/apache2/php.ini"
# Flutter Aliases
alias fl="flutter"
alias flr="flutter run"
alias fl:p="flutter pub"
alias fl:pa="flutter pub add"
alias dart:fa="dart fix --apply"
