# Base Aliases
alias ll="exa -lTargh -s=changed --level=1"
alias ll2="exa -lTargh -s=changed --level=2"
alias l="exa -lh"
alias la="exa -lah"
alias lg="exa -lgh"
alias cd="z"
alias cdi="zi"
alias ..="z .."
alias ...="z ../.."
alias ....="z ../../.."
alias cat="bat"
alias sn="sudo nano -miA"
alias n="nano -miA"
alias m="micro"
alias sm="sudo micro"
alias rmrf="rm -rf"
alias f="fuck"
alias fy="fuck -y"
# Activate Services
alias sys:start="sudo systemctl start"
alias sys:stop="sudo systemctl stop"
alias sys:status="sudo systemctl status"
alias sys:enable="sudo systemctl enable"
alias sys:disable="sudo systemctl disable"
alias sys:restart="sudo systemctl restart"
alias sys:reload="sudo systemctl reload"